FROM jessie

USER user

# nothing special - docker run will perform clone and npm install

# USER user
# RUN git clone https://github.com/QuantamHD/LucyJS.git /home/user/workspace
# WORKDIR /home/user/workspace
